[theme]
base = "light"
primaryColor = "#000000"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#0c0c0c"
font = "Noto Sans KR"

[server]
headless = true
port = 8501
enableCORS = false